### ISSUE TITLE
issues starting

### ISSUE THREAD

**Issue by alexgorbatchev** [crashsystems/gitlab-docker#13]
I'm having difficulty getting this to work...

```
$ uname -a
Linux devbox 3.8.0-29-generic #42~precise1-Ubuntu SMP Wed Aug 14 16:19:23 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux

$ docker version
Client version: 0.7.5
Go version (client): go1.2
Git commit (client): c348c04
Server version: 0.7.5
Git commit (server): c348c04
Go version (server): go1.2
Last stable version: 0.7.5
```

did the `docker pull` then `git clone` and only changed the FQDN host... then running

`docker run -d -v /root/gitlab-docker:/srv/gitlab -name gitlab crashsystems/gitlab-docker`

here's `docker logs`

```
Adding 'local diversion of /sbin/initctl to /sbin/initctl.distrib'
rm: cannot remove `/home/git/gitlab/tmp/pids/*': No such file or directory
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
Creating SSH2 RSA key; this may take some time ...
Creating SSH2 DSA key; this may take some time ...
Creating SSH2 ECDSA key; this may take some time ...
rake aborted!
Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/mysql2-0.3.11/lib/mysql2/client.rb:44:in `connect'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/mysql2-0.3.11/lib/mysql2/client.rb:44:in `initialize'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activerecord-4.0.2/lib/active_record/connection_adapters/mysql2_adapter.rb:18:in `new'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activerecord-4.0.2/lib/active_record/connection_adapters/mysql2_adapter.rb:18:in `mysql2_connection'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activerecord-4.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:440:in `new_connection'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activerecord-4.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:450:in `checkout_new_connection'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activerecord-4.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:421:in `acquire_connection'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activerecord-4.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:356:in `block in checkout'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activerecord-4.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:355:in `checkout'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activerecord-4.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:265:in `block in connection'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activerecord-4.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:264:in `connection'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activerecord-4.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:546:in `retrieve_connection'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activerecord-4.0.2/lib/active_record/connection_handling.rb:79:in `retrieve_connection'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activerecord-4.0.2/lib/active_record/connection_handling.rb:53:in `connection'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activerecord-4.0.2/lib/active_record/model_schema.rb:203:in `table_exists?'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/acts-as-taggable-on-2.4.1/lib/acts_as_taggable_on/acts_as_taggable_on/cache.rb:5:in `included'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/acts-as-taggable-on-2.4.1/lib/acts_as_taggable_on/taggable.rb:98:in `include'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/acts-as-taggable-on-2.4.1/lib/acts_as_taggable_on/taggable.rb:98:in `taggable_on'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/acts-as-taggable-on-2.4.1/lib/acts_as_taggable_on/taggable.rb:39:in `acts_as_taggable_on'
/home/git/gitlab/app/models/issue.rb:38:in `<class:Issue>'
/home/git/gitlab/app/models/issue.rb:20:in `<top (required)>'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `require'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `block in require'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:214:in `load_dependency'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `require'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:330:in `require_or_load'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:463:in `load_missing_constant'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:184:in `const_missing'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:495:in `load_missing_constant'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:184:in `const_missing'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:495:in `load_missing_constant'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:184:in `const_missing'
/home/git/gitlab/lib/api/notes.rb:6:in `<class:Notes>'
/home/git/gitlab/lib/api/notes.rb:3:in `<module:API>'
/home/git/gitlab/lib/api/notes.rb:1:in `<top (required)>'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `require'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `block in require'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:214:in `load_dependency'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `require'
/home/git/gitlab/lib/api/api.rb:1:in `block in <top (required)>'
/home/git/gitlab/lib/api/api.rb:1:in `each'
/home/git/gitlab/lib/api/api.rb:1:in `<top (required)>'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `require'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `block in require'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:214:in `load_dependency'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `require'
/home/git/gitlab/config/initializers/2_app.rb:13:in `block in <top (required)>'
/home/git/gitlab/config/initializers/2_app.rb:13:in `each'
/home/git/gitlab/config/initializers/2_app.rb:13:in `<top (required)>'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:223:in `load'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:223:in `block in load'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:214:in `load_dependency'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:223:in `load'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/railties-4.0.2/lib/rails/engine.rb:609:in `block (2 levels) in <class:Engine>'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/railties-4.0.2/lib/rails/engine.rb:608:in `each'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/railties-4.0.2/lib/rails/engine.rb:608:in `block in <class:Engine>'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/railties-4.0.2/lib/rails/initializable.rb:30:in `instance_exec'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/railties-4.0.2/lib/rails/initializable.rb:30:in `run'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/railties-4.0.2/lib/rails/initializable.rb:55:in `block in run_initializers'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/railties-4.0.2/lib/rails/initializable.rb:44:in `each'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/railties-4.0.2/lib/rails/initializable.rb:44:in `tsort_each_child'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/railties-4.0.2/lib/rails/initializable.rb:54:in `run_initializers'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/railties-4.0.2/lib/rails/application.rb:215:in `initialize!'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/railties-4.0.2/lib/rails/railtie/configurable.rb:30:in `method_missing'
/home/git/gitlab/config/environment.rb:5:in `<top (required)>'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `require'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `block in require'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:214:in `load_dependency'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `require'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/railties-4.0.2/lib/rails/application.rb:189:in `require_environment!'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/railties-4.0.2/lib/rails/application.rb:250:in `block in run_tasks_blocks'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/sprockets-rails-2.0.1/lib/sprockets/rails/task.rb:54:in `block (2 levels) in define'
Tasks: TOP => environment
(See full trace by running task with --trace)
140115 05:46:45 mysqld_safe Can't log to error log and syslog at the same time.  Remove all --log-error configuration options for --syslog to take effect.
140115 05:46:45 mysqld_safe Logging to '/var/log/mysql/error.log'.
140115 05:46:45 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
gitlabhq_production already exists
-- create_table("broadcast_messages", {:force=>true})
   -> 0.0206s
-- create_table("deploy_keys_projects", {:force=>true})
   -> 0.0037s
-- add_index("deploy_keys_projects", ["project_id"], {:name=>"index_deploy_keys_projects_on_project_id", :using=>:btree})
   -> 0.0125s
-- create_table("events", {:force=>true})
   -> 0.0045s
-- add_index("events", ["action"], {:name=>"index_events_on_action", :using=>:btree})
   -> 0.0072s
-- add_index("events", ["author_id"], {:name=>"index_events_on_author_id", :using=>:btree})
   -> 0.0094s
-- add_index("events", ["created_at"], {:name=>"index_events_on_created_at", :using=>:btree})
   -> 0.0106s
-- add_index("events", ["project_id"], {:name=>"index_events_on_project_id", :using=>:btree})
   -> 0.0079s
-- add_index("events", ["target_id"], {:name=>"index_events_on_target_id", :using=>:btree})
   -> 0.0075s
-- add_index("events", ["target_type"], {:name=>"index_events_on_target_type", :using=>:btree})
   -> 0.0095s
-- create_table("forked_project_links", {:force=>true})
   -> 0.0037s
-- add_index("forked_project_links", ["forked_to_project_id"], {:name=>"index_forked_project_links_on_forked_to_project_id", :unique=>true, :using=>:btree})
   -> 0.0077s
-- create_table("issues", {:force=>true})
   -> 0.0059s
-- add_index("issues", ["assignee_id"], {:name=>"index_issues_on_assignee_id", :using=>:btree})
   -> 0.0074s
-- add_index("issues", ["author_id"], {:name=>"index_issues_on_author_id", :using=>:btree})
   -> 0.0153s
-- add_index("issues", ["created_at"], {:name=>"index_issues_on_created_at", :using=>:btree})
   -> 0.0101s
-- add_index("issues", ["milestone_id"], {:name=>"index_issues_on_milestone_id", :using=>:btree})
   -> 0.0084s
-- add_index("issues", ["project_id"], {:name=>"index_issues_on_project_id", :using=>:btree})
   -> 0.0082s
-- add_index("issues", ["title"], {:name=>"index_issues_on_title", :using=>:btree})
   -> 0.0088s
-- create_table("keys", {:force=>true})
   -> 0.0039s
-- add_index("keys", ["user_id"], {:name=>"index_keys_on_user_id", :using=>:btree})
   -> 0.0090s
-- create_table("merge_requests", {:force=>true})
   -> 0.0045s
-- add_index("merge_requests", ["assignee_id"], {:name=>"index_merge_requests_on_assignee_id", :using=>:btree})
   -> 0.0071s
-- add_index("merge_requests", ["author_id"], {:name=>"index_merge_requests_on_author_id", :using=>:btree})
   -> 0.0086s
-- add_index("merge_requests", ["created_at"], {:name=>"index_merge_requests_on_created_at", :using=>:btree})
   -> 0.0088s
-- add_index("merge_requests", ["milestone_id"], {:name=>"index_merge_requests_on_milestone_id", :using=>:btree})
   -> 0.0069s
-- add_index("merge_requests", ["source_branch"], {:name=>"index_merge_requests_on_source_branch", :using=>:btree})
   -> 0.0111s
-- add_index("merge_requests", ["source_project_id"], {:name=>"index_merge_requests_on_project_id", :using=>:btree})
   -> 0.0098s
-- add_index("merge_requests", ["target_branch"], {:name=>"index_merge_requests_on_target_branch", :using=>:btree})
   -> 0.0103s
-- add_index("merge_requests", ["title"], {:name=>"index_merge_requests_on_title", :using=>:btree})
   -> 0.0101s
-- create_table("milestones", {:force=>true})
   -> 0.0046s
-- add_index("milestones", ["due_date"], {:name=>"index_milestones_on_due_date", :using=>:btree})
   -> 0.0077s
-- add_index("milestones", ["project_id"], {:name=>"index_milestones_on_project_id", :using=>:btree})
   -> 0.0082s
-- create_table("namespaces", {:force=>true})
   -> 0.0068s
-- add_index("namespaces", ["name"], {:name=>"index_namespaces_on_name", :using=>:btree})
   -> 0.0106s
-- add_index("namespaces", ["owner_id"], {:name=>"index_namespaces_on_owner_id", :using=>:btree})
   -> 0.0084s
-- add_index("namespaces", ["path"], {:name=>"index_namespaces_on_path", :using=>:btree})
   -> 0.0080s
-- add_index("namespaces", ["type"], {:name=>"index_namespaces_on_type", :using=>:btree})
   -> 0.0082s
-- create_table("notes", {:force=>true})
   -> 0.0342s
-- add_index("notes", ["author_id"], {:name=>"index_notes_on_author_id", :using=>:btree})
   -> 0.0085s
-- add_index("notes", ["commit_id"], {:name=>"index_notes_on_commit_id", :using=>:btree})
   -> 0.0096s
-- add_index("notes", ["created_at"], {:name=>"index_notes_on_created_at", :using=>:btree})
   -> 0.0080s
-- add_index("notes", ["noteable_id", "noteable_type"], {:name=>"index_notes_on_noteable_id_and_noteable_type", :using=>:btree})
   -> 0.0072s
-- add_index("notes", ["noteable_type"], {:name=>"index_notes_on_noteable_type", :using=>:btree})
   -> 0.0109s
-- add_index("notes", ["project_id", "noteable_type"], {:name=>"index_notes_on_project_id_and_noteable_type", :using=>:btree})
   -> 0.0076s
-- add_index("notes", ["project_id"], {:name=>"index_notes_on_project_id", :using=>:btree})
   -> 0.0066s
-- create_table("projects", {:force=>true})
   -> 0.0053s
-- add_index("projects", ["creator_id"], {:name=>"index_projects_on_owner_id", :using=>:btree})
   -> 0.0072s
-- add_index("projects", ["last_activity_at"], {:name=>"index_projects_on_last_activity_at", :using=>:btree})
   -> 0.0105s
-- add_index("projects", ["namespace_id"], {:name=>"index_projects_on_namespace_id", :using=>:btree})
   -> 0.0131s
-- create_table("protected_branches", {:force=>true})
   -> 0.0116s
-- add_index("protected_branches", ["project_id"], {:name=>"index_protected_branches_on_project_id", :using=>:btree})
   -> 0.0079s
-- create_table("services", {:force=>true})
   -> 0.0041s
-- add_index("services", ["project_id"], {:name=>"index_services_on_project_id", :using=>:btree})
   -> 0.0116s
-- create_table("snippets", {:force=>true})
   -> 0.0091s
-- add_index("snippets", ["author_id"], {:name=>"index_snippets_on_author_id", :using=>:btree})
   -> 0.0066s
-- add_index("snippets", ["created_at"], {:name=>"index_snippets_on_created_at", :using=>:btree})
   -> 0.0062s
-- add_index("snippets", ["expires_at"], {:name=>"index_snippets_on_expires_at", :using=>:btree})
   -> 0.0081s
-- add_index("snippets", ["project_id"], {:name=>"index_snippets_on_project_id", :using=>:btree})
   -> 0.0063s
-- create_table("taggings", {:force=>true})
   -> 0.0083s
-- add_index("taggings", ["tag_id"], {:name=>"index_taggings_on_tag_id", :using=>:btree})
   -> 0.0078s
-- add_index("taggings", ["taggable_id", "taggable_type", "context"], {:name=>"index_taggings_on_taggable_id_and_taggable_type_and_context", :using=>:btree})
   -> 0.0076s
-- create_table("tags", {:force=>true})
   -> 0.0040s
-- create_table("users", {:force=>true})
   -> 0.0087s
-- add_index("users", ["admin"], {:name=>"index_users_on_admin", :using=>:btree})
   -> 0.0095s
-- add_index("users", ["authentication_token"], {:name=>"index_users_on_authentication_token", :unique=>true, :using=>:btree})
   -> 0.0116s
-- add_index("users", ["confirmation_token"], {:name=>"index_users_on_confirmation_token", :unique=>true, :using=>:btree})
   -> 0.0122s
-- add_index("users", ["email"], {:name=>"index_users_on_email", :unique=>true, :using=>:btree})
   -> 0.0092s
-- add_index("users", ["extern_uid", "provider"], {:name=>"index_users_on_extern_uid_and_provider", :unique=>true, :using=>:btree})
   -> 0.0099s
-- add_index("users", ["name"], {:name=>"index_users_on_name", :using=>:btree})
   -> 0.0153s
-- add_index("users", ["reset_password_token"], {:name=>"index_users_on_reset_password_token", :unique=>true, :using=>:btree})
   -> 0.0097s
-- add_index("users", ["username"], {:name=>"index_users_on_username", :using=>:btree})
   -> 0.0210s
-- create_table("users_groups", {:force=>true})
   -> 0.0048s
-- add_index("users_groups", ["user_id"], {:name=>"index_users_groups_on_user_id", :using=>:btree})
   -> 0.0070s
-- create_table("users_projects", {:force=>true})
   -> 0.0042s
-- add_index("users_projects", ["project_access"], {:name=>"index_users_projects_on_project_access", :using=>:btree})
   -> 0.0078s
-- add_index("users_projects", ["project_id"], {:name=>"index_users_projects_on_project_id", :using=>:btree})
   -> 0.0107s
-- add_index("users_projects", ["user_id"], {:name=>"index_users_projects_on_user_id", :using=>:btree})
   -> 0.0067s
-- create_table("web_hooks", {:force=>true})
   -> 0.0042s
-- add_index("web_hooks", ["project_id"], {:name=>"index_web_hooks_on_project_id", :using=>:btree})
   -> 0.0090s
-- initialize_schema_migrations_table()
   -> 0.0176s

== Seed from /home/git/gitlab/db/fixtures/production/001_admin.rb
2014-01-15T05:47:01Z 503 TID-ot6thjsz8 INFO: Sidekiq client with redis options {:url=>"redis://localhost:6379", :namespace=>"resque:gitlab"}

Administrator account created:

login.........admin@local.host
password......5iveL!fe
[deprecated] I18n.enforce_available_locales will default to true in the future. If you really want to skip validation of your locale you can set I18n.enforce_available_locales = false to avoid this message.
rake aborted!
Validation failed: Email has already been taken, Username has already been taken, Username already exist
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/seed-fu-2.3.0/lib/seed-fu/runner.rb:46:in `eval'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activerecord-4.0.2/lib/active_record/attribute_methods/dirty.rb:41:in `save!'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activerecord-4.0.2/lib/active_record/transactions.rb:275:in `block in save!'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activerecord-4.0.2/lib/active_record/transactions.rb:326:in `block in with_transaction_returning_status'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activerecord-4.0.2/lib/active_record/connection_adapters/abstract/database_statements.rb:200:in `transaction'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activerecord-4.0.2/lib/active_record/transactions.rb:209:in `transaction'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activerecord-4.0.2/lib/active_record/transactions.rb:323:in `with_transaction_returning_status'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activerecord-4.0.2/lib/active_record/transactions.rb:275:in `save!'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/state_machine-1.2.0/lib/state_machine/integrations/active_record.rb:487:in `block in save!'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/state_machine-1.2.0/lib/state_machine/integrations/active_record.rb:502:in `block (2 levels) in around_save'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/state_machine-1.2.0/lib/state_machine/transition_collection.rb:150:in `block in run_actions'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/state_machine-1.2.0/lib/state_machine/transition_collection.rb:170:in `catch_exceptions'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/state_machine-1.2.0/lib/state_machine/transition_collection.rb:148:in `run_actions'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/state_machine-1.2.0/lib/state_machine/transition_collection.rb:133:in `run_callbacks'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/state_machine-1.2.0/lib/state_machine/transition_collection.rb:212:in `run_callbacks'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/state_machine-1.2.0/lib/state_machine/transition_collection.rb:63:in `block (2 levels) in perform'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/state_machine-1.2.0/lib/state_machine/transition_collection.rb:63:in `catch'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/state_machine-1.2.0/lib/state_machine/transition_collection.rb:63:in `block in perform'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/state_machine-1.2.0/lib/state_machine/transition_collection.rb:186:in `within_transaction'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/state_machine-1.2.0/lib/state_machine/transition_collection.rb:62:in `perform'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/state_machine-1.2.0/lib/state_machine/integrations/active_record.rb:502:in `block in around_save'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/state_machine-1.2.0/lib/state_machine/integrations/active_record.rb:530:in `block in transaction'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activerecord-4.0.2/lib/active_record/connection_adapters/abstract/database_statements.rb:200:in `transaction'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activerecord-4.0.2/lib/active_record/transactions.rb:209:in `transaction'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/state_machine-1.2.0/lib/state_machine/integrations/active_record.rb:529:in `transaction'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/state_machine-1.2.0/lib/state_machine/integrations/active_record.rb:501:in `around_save'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/state_machine-1.2.0/lib/state_machine/integrations/active_record.rb:487:in `save!'
(eval):14:in `block (2 levels) in run_file'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/seed-fu-2.3.0/lib/seed-fu/runner.rb:46:in `eval'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/seed-fu-2.3.0/lib/seed-fu/runner.rb:46:in `block (2 levels) in run_file'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/seed-fu-2.3.0/lib/seed-fu/runner.rb:58:in `block in open'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/seed-fu-2.3.0/lib/seed-fu/runner.rb:57:in `open'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/seed-fu-2.3.0/lib/seed-fu/runner.rb:57:in `open'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/seed-fu-2.3.0/lib/seed-fu/runner.rb:36:in `block in run_file'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activerecord-4.0.2/lib/active_record/connection_adapters/abstract/database_statements.rb:202:in `block in transaction'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activerecord-4.0.2/lib/active_record/connection_adapters/abstract/database_statements.rb:210:in `within_new_transaction'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activerecord-4.0.2/lib/active_record/connection_adapters/abstract/database_statements.rb:202:in `transaction'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activerecord-4.0.2/lib/active_record/transactions.rb:209:in `transaction'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/seed-fu-2.3.0/lib/seed-fu/runner.rb:35:in `run_file'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/seed-fu-2.3.0/lib/seed-fu/runner.rb:26:in `block in run'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/seed-fu-2.3.0/lib/seed-fu/runner.rb:25:in `each'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/seed-fu-2.3.0/lib/seed-fu/runner.rb:25:in `run'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/seed-fu-2.3.0/lib/seed-fu.rb:29:in `seed'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/seed-fu-2.3.0/lib/tasks/seed_fu.rake:36:in `block (2 levels) in <top (required)>'
Tasks: TOP => db:seed_fu
(See full trace by running task with --trace)

== Seed from /home/git/gitlab/db/fixtures/production/001_admin.rb
140115 05:47:19 mysqld_safe Can't log to error log and syslog at the same time.  Remove all --log-error configuration options for --syslog to take effect.
Starting both the GitLab Unicorn and Sidekiq140115 05:47:19 mysqld_safe Logging to '/var/log/mysql/error.log'.
140115 05:47:19 mysqld_safe A mysqld process already exists
..
The GitLab Unicorn web server with pid 903 is running.
The GitLab Sidekiq job dispatcher with pid 913 is running.
GitLab and all its components are up and running.
Starting nginx: nginx.
Mysql2::Error: Can't create database 'gitlabhq_production'; database exists: CREATE DATABASE `gitlabhq_production` DEFAULT CHARACTER SET `utf8` COLLATE `utf8_unicode_ci`
master failed to start, check stderr log for details
  Rendered devise/mailer/confirmation_instructions.html.erb (1.9ms)
  Rendered notify/new_user_email.html.haml within layouts/notify (4.0ms)
  Rendered notify/new_user_email.text.erb (0.9ms)

Sent mail to admin@local.host (120263.1ms)

Sent mail to admin@local.host (120073.9ms)
```

**Comment by crashsystems** [comment]
What specifically are you having trouble with? Is the container stopping?
Are you unable to reach the host?
